export const searchData = [
  {
    title: "Inicio",
    description: "Página de bienvenida de Nikoll Bonilla Hancco",
    path: "/",
    keywords: [
      "home",
      "inicio",
      "cv",
      "resume",
      "portafolio",
      "nikoll",
      "nikoll bonilla hancco",
      "fullstack",
      "frontend specialist",
      "react",
      "nextjs",
      "threejs",
      "fastapi",
      "flutter",
    ],
  },
  {
    title: "Sobre Mí",
    description: "Conoce más sobre mi trayectoria y experiencia",
    path: "/about",
    keywords: [
      "about",
      "sobre mi",
      "perfil",
      "experiencia",
      "bio",
      "cv",
      "resume",
      "nikoll",
      "bonilla",
      "hancco",
      "fullstack",
      "frontend",
      "desarrolladora",
    ],
  },
  {
    title: "Educación",
    description: "Mi formación técnica en TECSUP y cursos de especialización",
    path: "/education",
    keywords: [
      "educacion",
      "tecsup",
      "platzi",
      "titulo",
      "desarrollo de software",
      "diseño y desarrollo de software",
      "linux",
      "git",
    ],
  },
  {
    title: "Experiencia",
    description: "Mi trayectoria profesional en Navia y TECSUP",
    path: "/experience",
    keywords: [
      "experiencia",
      "trabajo",
      "carrera",
      "navia",
      "tecsup",
      "simuladores 3d",
      "scorm",
      "react",
      "fastapi",
      "flutter",
    ],
  },
  {
    title: "Habilidades",
    description: "Mis habilidades técnicas en desarrollo web, 3D y móvil",
    path: "/skills",
    keywords: [
      "skills",
      "habilidades",
      "tecnologias",
      "react",
      "nextjs",
      "threejs",
      "webgl",
      "fastapi",
      "python",
      "flutter",
      "dart",
      "docker",
      "scorm",
    ],
  },
  {
    title: "Proyectos",
    description: "Laboratorios virtuales 3D, plataformas e-learning y soluciones web",
    path: "/projects",
    keywords: [
      "proyectos",
      "portafolio",
      "code",
      "simuladores 3d",
      "laboratorios virtuales",
      "react",
      "threejs",
      "fastapi",
    ],
  },
  {
    title: "Certificados y Reconocimientos",
    description: "Reconocimientos, premios y certificaciones obtenidas",
    path: "/certificates",
    keywords: [
      "certificados",
      "reconocimientos",
      "premios",
      "jinis",
      "hult prize",
      "spia",
      "platzi",
      "innovacion tecnologica",
    ],
  },
];


